# Generated by Django 5.2.7 on 2025-10-24 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('understanding_rating', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Rate your understanding (1-5)')),
                ('difficulty_rating', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Rate difficulty (1-5)')),
                ('helpful_rating', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Rate helpfulness (1-5)')),
                ('comments', models.TextField(blank=True)),
                ('concepts_learned', models.TextField(blank=True, help_text='What concepts did you learn?')),
                ('questions_arose', models.TextField(blank=True, help_text='What questions do you have?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('simulation_type', models.CharField(choices=[('motion', 'Motion & Mechanics'), ('electricity', 'Electricity & Magnetism'), ('optics', 'Optics & Light'), ('waves', 'Waves & Sound'), ('thermodynamics', 'Thermodynamics'), ('quantum', 'Quantum Physics'), ('relativity', 'Relativity')], max_length=20)),
                ('html_content', models.TextField(help_text='HTML/JavaScript simulation code')),
                ('css_content', models.TextField(blank=True, help_text='Custom CSS for simulation')),
                ('js_content', models.TextField(blank=True, help_text='JavaScript code for simulation')),
                ('parameters', models.JSONField(default=dict, help_text='Simulation parameters and default values')),
                ('learning_objectives', models.TextField(help_text='What students will learn from this simulation')),
                ('instructions', models.TextField(help_text='How to use the simulation')),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('is_interactive', models.BooleanField(default=True)),
                ('estimated_duration', models.PositiveIntegerField(default=10, help_text='Estimated time in minutes')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to='topics.physicstopic')),
            ],
            options={
                'ordering': ['topic__grade__order', 'topic__order', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SimulationParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parameter_type', models.CharField(choices=[('slider', 'Slider'), ('input', 'Text Input'), ('dropdown', 'Dropdown'), ('checkbox', 'Checkbox'), ('color', 'Color Picker')], max_length=20)),
                ('default_value', models.CharField(max_length=200)),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('step', models.FloatField(blank=True, null=True)),
                ('options', models.JSONField(blank=True, help_text='Options for dropdown parameters', null=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters_list', to='simulations.simulation')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SimulationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Duration in seconds', null=True)),
                ('parameters_used', models.JSONField(default=dict, help_text='Parameters user experimented with')),
                ('interactions_count', models.PositiveIntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='simulations.simulation')),
            ],
        ),
    ]
